name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet!
        run: echo "Welcome, Jabroni!"
      - name: Bye!
        run: echo "Goodbye, Jabroni!"
